matrix:
  include:
    - language: python
      python: "3.6"
      install:
        - pipenv install --ignore-pipfile

      script:

        - pipenv run flake8 formater.py
        - pipenv run python formater.py --gryc -i ./tests/GRYC/ -o ./tests/GRYC/to_test_GRYC
        - pipenv run diff ./tests/GRYC/to_test_GRYC.txt ./tests/GRYC/test_GRYC.txt
        - pipenv run python formater.py --go -i tests/GO/GO_input_test.obo -o tests/GO/to_test_GO
        - pipenv run diff ./tests/GO/to_test_GO.txt ./tests/GO/test_GO.txt
        - pipenv run python formater.py --mesh -i tests/MESH/MESH_input_test.bin -o tests/MESH/test_MESH
        - pipenv run diff ./tests/MESH/to_test_MESH.txt ./tests/MESH/test_MESH.txt

      after_success:
        - coveralls

    - language: r
      cache: packages
      sudo: false
      addons:
      apt:
        sources:
        - r-packages-precise
        packages:
        - r-base-dev
      script:
        - Rscript ./tests/install_Ytools.R
