language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install
script:
  - pipenv run python ./MESH_link/MESH_link.py -m ./MESH_link/Mesh_file/d2018.bin -o ./MESH_link/Outputs/Mesh_link_table_2018
